### ISSUE TITLE
jaxonのhandのangle-vectorを送っているメソッドはどれでしょうか？

### ISSUE THREAD

**Issue by snozawa** [start-jsk/rtmros_tutorials#422]
jaxonのhandのangle-vectorを送っているメソッドはどれでしょうか？
https://github.com/start-jsk/rtmros_tutorials/blob/master/hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l#L31
これ？

**Comment by mmurooka** [comment]
はい，そこです．
https://github.com/start-jsk/rtmros_tutorials/blob/master/hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l#L14 で
https://github.com/jsk-ros-pkg/trans_system/blob/master/thk_hand_controller/euslisp/thkhand-simple-controller.l#L52 にいきます．

**Comment by snozawa** [comment]
基本は片手につき1個のスカラーをsendするイメーじでいいかな？

**Comment by mmurooka** [comment]
はい，1が開く，0が閉じるです．

https://github.com/jsk-ros-pkg/trans_system/blob/master/thk_hand_controller/euslisp/thkhand-simple-controller.l#L75

https://github.com/jsk-ros-pkg/trans_system/blob/master/thk_hand_controller/euslisp/thkhand-simple-controller.l#L79

**Comment by snozawa** [comment]
関節角度的なものはあるんだっけ？

**Comment by mmurooka** [comment]
> はい，1が開く，0が閉じるです．

0.5が半開きとなっていて，[0:1]の連続な数値が与えられます．

現在の関節角は，
https://github.com/jsk-ros-pkg/trans_system/blob/master/thk_hand_controller/euslisp/thkhand-simple-controller.l#L119
でとれます．
これも（確か），[0:1]の間の値が返って来ます．

**Comment by snozawa** [comment]
了解です、ありがとうございます。

**Comment by mmurooka** [comment]
https://github.com/jsk-ros-pkg/trans_system/pull/525 でREADMEを追加しました．
