### ISSUE TITLE
Unable to resolve paths for JAXON_RED.urdf.xacro

### ISSUE THREAD

**Issue by sktometometo** [start-jsk/rtmros_tutorials#601]
[JAXON_RED.urdf.xacro]() includes JAXON_RED_body.urdf.xacro. But it does not exist. Where is it?

**Comment by Naoki-Hiraoka** [comment]
It is auto-generated file.

https://github.com/start-jsk/rtmros_tutorials/blob/2edfaf5ef6c35ffdd5bbfb6799dd5c2090f31c8c/hrpsys_ros_bridge_tutorials/CMakeLists.txt#L538
https://github.com/start-jsk/rtmros_tutorials/blob/2edfaf5ef6c35ffdd5bbfb6799dd5c2090f31c8c/hrpsys_ros_bridge_tutorials/CMakeLists.txt#L735

To generate ` JAXON_RED_body.urdf`, you have to build `hrpsys_ros_bridge_tutorials` with `jsk_models`(private).

**Comment by sktometometo** [comment]
Thanks, I understand.

**Comment by knorth55** [comment]
FYU: https://github.com/jsk-enshu/robot-programming/blob/master/cart_humanoid/urdf/JAXON_RED.urdf.xacro
